---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: webapp
rules:
- apiGroups:
  - monitoring.httpcheck.io
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.httpcheck.io
  resources:
  - cronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.httpcheck.io
  resources:
  - cronjobs/status
  verbs:
  - get
  - patch
  - update
